apiVersion: v1
kind: ServiceAccount
metadata:
  name: knot
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: knot
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: knot
  name: knot
spec:
  #ttlSecondsAfterFinished: 3600
  backoffLimit: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: knot
    spec:
      serviceAccount: knot
      containers:
        - image: garreeoke/knot
          name: knot
          env:
            - name: KNOT_TYPE
              value: "github"
            - name: KNOT_AUTH
              value: "cluster"
            - name: KNOT_URI
              value: "owner/garreeoke/repository/k8_setup/branch/master"
            #- name: GITHUB_USER
            #  value: ""
            #- name: GITHUB_TOKEN
            #  value: ""
          resources: {}
      restartPolicy: OnFailure
status: {}